### PR TITLE
Fix #357 - invalid characters in path/query

### LINKED ISSUE #218: Character encoding issue in Uri.php filterQuery() method.
In example when the query string contains something like this: "?name=value&név=érték" in internet explorer the browser does not send it as utf-8 encoded, the result is "?name=value&n?v=?rt?k".
It is a known bug in [Internet Explorer browsers](https://blogs.msdn.microsoft.com/ieinternals/2014/04/22/unicode-in-url-changes-for-ie11/).
Possible workaround is checking return value of `filterQueryOrFragment()` for null value (because `filterQueryOrFragment()` returns null on failure) and call `filterQueryOrFragment()` again but the input have to run through `utf8_encode()`  function. All together: `filterQueryOrFragment(utf8_encode(<query_string_here>))`.
As far as I know other browsers are not affected by this bug, e.g.: Mozilla Firefox, Google Chrome, Opera browser (current versions).

### LINKED ISSUE #357: Uncaught TypeError: Return value of Zend\\Diactoros\\Uri::filterQueryOrFragment() must be of the type string, null returned
```
PHP Fatal error:  Uncaught TypeError: Return value of Zend\\Diactoros\\Uri::filterQueryOrFragment() must be of the type string, null returned in /vendor/zendframework/zend-diactoros/src/Uri.php:660\n
Stack trace:\n
#0 /vendor/zendframework/zend-diactoros/src/Uri.php(618): Zend\\Diactoros\\Uri->filterQueryOrFragment('\\xCF')\n
#1 /vendor/zendframework/zend-diactoros/src/Uri.php(410): Zend\\Diactoros\\Uri->filterQuery('Keyword=\\xCF')\n
#2 /vendor/zendframework/zend-diactoros/src/functions/marshal_uri_from_sapi.php(218): Zend\\Diactoros\\Uri->withQuery('Keyword=\\xCF3')\n
```

Version
 zend-diactoros 2.1.1
 php 7.2.5
### Expected results

TypeError does not occur

### PR DESCRIPTION
**Pull request by webimpress**
Fixes #357 
Fixes #218

### CODE REVIEW

**Comment by webimpress** [comment]
@weierophinney I was looking for right solution of this issue, and I think I have found one finally.
In my opinion we need to do something with invalid characters - in that case encode - what I mean we can't just throw exception, as these can be user input.
So if invalid UTF-8 character is detected in the string, then I am checking the string letter by letter to encode that invalid character. This solution run regexp on one character in the loop, but I couldn't find anything better. Any suggestions appreciated. 

/cc @YellowPepper @krowinski @freyr @oroszlanyzsolt

File: src/Uri.php [hunk 1]
```diff
@@ -594,6 +598,25 @@ private function filterPath(string $path) : string
...
+    /**
+     * Encode invalid UTF-8 characters in given string. All other characters are unchanged.
+     */
+    private function filterInvalidUtf8(string $string) : string
+    {
+        if (preg_match('//u', $string)) {
+            return $string;
+        }
+
+        $letters = str_split($string);
```
Comment (weierophinney) [inline src/Uri.php]: Noting here, because I had to look it up - `str_split()` splits into bytes instead of characters when it encounters a multibyte string.

File: src/Uri.php [hunk 2]
```diff
@@ -594,6 +598,25 @@ private function filterPath(string $path) : string
         return '/' . ltrim($path, '/');
     }
 
+    /**
+     * Encode invalid UTF-8 characters in given string. All other characters are unchanged.
+     */
+    private function filterInvalidUtf8(string $string) : string
+    {
+        if (preg_match('//u', $string)) {
```
Comment (weierophinney) [inline src/Uri.php]: I don't understand what this is doing, exactly.

I've tried it locally with a variety of strings from your query provider below, and every single one of them results in a positive match, which means the logic below never gets hit. Maybe you're not testing _invalid_ UTF-8 characters anywhere?

Comment (webimpress) [reply src/Uri.php]: How come?

See: https://3v4l.org/MEYgF

```php
var_dump(preg_match('//u', "\x21\x92"));
```

result:
```
bool(false)
```

Somehow test I've added works.

Comment (weierophinney) [reply src/Uri.php]: Turned out I was using single quotes instead of double quotes when I was doing my tests here. Once I changed the quoting style, I was able to observe the same behaviour finally.

Might be good to drop a note in indicating what this is doing, though, so future contributors/maintainers know the purpose.

**Comment by krowinski** [comment]
tx for fix!
