### PR TITLE
Alternate fixes #192

### LINKED ISSUE #192: Unexpected symbol
```PHP
$uri = new Zend\Diactoros\Uri;

$uri = $uri
	->withHost('google.com');
// string(11) "google.com:" 
var_dump((string)$uri);
```

### PR DESCRIPTION
**Pull request by samsonasik**
Alternate fixes #192

### CODE REVIEW

File: test/UriTest.php [hunk 1]
```diff
@@ -568,4 +568,11 @@ public function testUtf8Uri()
 
         $this->assertEquals('ουτοπία.δπθ.gr', $uri->getHost());
     }
+
+    public function testUriDoesNotAppendColonToHostIfPortIsEmpty()
+    {
+        $uri = (new Uri())->withHost('google.com');
+        $this->assertEquals('google.com', (string) $uri);
+        $this->assertNotEquals('google.com:', (string) $uri);
```
Comment (snapshotpl) [inline test/UriTest.php]: Is it make a sense if you have a `assertEquals`?

Comment (samsonasik) [inline test/UriTest.php]: yes, I can remove if requested

**Comment by weierophinney** [comment]
Thanks, @samsonasik. I made the change suggested by @snapshotpl on merge.
