### PR TITLE
Modify detection of HTTPS

### LINKED ISSUE #362: marshallHttps incorrectly detects HTtPS-connection
- [x] I was not able to find an [open](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/c/questions/expressive).)

[MarshallHttpsValue](https://github.com/zendframework/zend-diactoros/blame/37bf68b428850ee26ed7c3be6c26236dd95a95f1/src/functions/marshal_uri_from_sapi.php#L171) tries to detect whether the curent connection is an encryptesd one by trying to detect whether `$_SERVER['HTTPS']` exists and does not contain `off`.

According to the [nginx-Documentation](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_https) that is a problematic approach as in case of an unencrypted connection the 'HTTPS'-key will contain an empty string which will then be resolved to `true` as it is not the string `off`. I doubt that that is intended behaviour.

### Code to reproduce the issue

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$server = [
    "HTTPS" => "",
    "SERVER_NAME"=> "localhost",
    "SERVER_PORT"=>"80",
    "SERVER_ADDR"=> "172.22.0.4",
    "REMOTE_PORT"=> "36852",
    "REMOTE_ADDR" =>  "172.22.0.1",
    "SERVER_SOFTWARE" =>  "nginx/1.11.8",
    "GATEWAY_INTERFACE" =>  "CGI/1.1",
    "SERVER_PROTOCOL" =>  "HTTP/1.1",
    "DOCUMENT_ROOT" => "/var/www/public",
    "DOCUMENT_URI" => "/index.php",
    "REQUEST_URI" =>  "/api/messagebox-schema",
    "PATH_TRANSLATED" => "/var/www/public",
    "PATH_INFO" => "",
    "SCRIPT_NAME" => "/index.php",
    "CONTENT_LENGTH" => "",
    "CONTENT_TYPE" => "",
    "REQUEST_METHOD" => "GET",
    "QUERY_STRING" => "",
    "SCRIPT_FILENAME" => "/var/www/public/index.php",
    "FCGI_ROLE" => "RESPONDER",
    "PHP_SELF" => "/index.php",
    ];

$headers = [
    "HTTP_COOKIE" => '',
    "HTTP_ACCEPT_LANGUAGE" => "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
    "HTTP_ACCEPT_ENCODING" => "gzip, deflate, br",
    "HTTP_REFERER" => "http://localhost:8080/index.html",
    "HTTP_USER_AGENT" => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/67.0.3396.99 Chrome/67.0.3396.99 Safari/537.36",
    "HTTP_ACCEPT" => "application/json,*/*",
    "HTTP_CONNECTION" => "keep-alive",
    "HTTP_HOST" => "localhost:8080",
];

echo (string) \Zend\Diactoros\marshalUriFromSapi($server, $headers) . "\n";
```

### Expected results

`http://localhost:80/api/messagebox-schema`

### Actual results

`https://localhost:80/api/messagebox-schema`

### PR DESCRIPTION
**Pull request by heiglandreas**
This modifies the detection of HTTPS by checking whether the lower-case value of the HTTPS-key of the server variable equals 'on'. Before that checked whether the value did *not* match 'off' which meant that the nginx-default for non-HTTPS connections (which, according to the [documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_https) is an empty string) did in fact match and returned that the connection *is* encrypted.

This fixes #362

Provide a narrative description of what you are trying to accomplish: See #362 

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [x] Add a `CHANGELOG.md` entry for the fix.

### CODE REVIEW

File: test/functions/MarshalUriFromSapiTest.php [hunk 1]
```diff
@@ -0,0 +1,72 @@
+<?php
+/**
+ * @see       https://github.com/zendframework/zend-diactoros for the canonical source repository
+ * @copyright Copyright (c) 2018 Zend Technologies USA Inc. (http://www.zend.com)
```
Comment (webimpress) [inline test/functions/MarshalUriFromSapiTest.php]: 2019 please

File: test/functions/MarshalUriFromSapiTest.php [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+use function Zend\Diactoros\marshalUriFromSapi;
+
+class MarshalUriFromSapiTest extends TestCase
+{
+    /** @dataProvider returnsUrlWithCorrectHttpSchemeFromArraysProvider */
+    public function testReturnsUrlWithCorrectHttpSchemeFromArrays(string $httpsValue, string $expectedScheme) : void
+    {
+        $server = [
+            "HTTPS" => $httpsValue,
+            "SERVER_NAME"=> "localhost",
```
Comment (webimpress) [inline test/functions/MarshalUriFromSapiTest.php]: please use single quotes and always one space before and after `=>`.

File: test/functions/MarshalUriFromSapiTest.php [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+declare(strict_types = 1);
+
+namespace ZendTest\Diactoros\functions;
+
+use PHPUnit\Framework\TestCase;
+use function Zend\Diactoros\marshalUriFromSapi;
+
+class MarshalUriFromSapiTest extends TestCase
+{
+    /** @dataProvider returnsUrlWithCorrectHttpSchemeFromArraysProvider */
```
Comment (webimpress) [inline test/functions/MarshalUriFromSapiTest.php]: please use multiline PHPDoc for method doc-comment:
```php
/**
 * @dataProvider returnsUrlWithCorrectHttpSchemeFromArraysProvider
 */
```

File: test/functions/MarshalUriFromSapiTest.php [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+     * @param string $httpsValue
+     * @param string $expectedScheme
+     * @dataProvider returnsUrlWithCorrectHttpSchemeFromArraysProvider
+     */
+    public function testReturnsUrlWithCorrectHttpSchemeFromArrays(string $httpsValue, string $expectedScheme) : void
+    {
+        $server = [
+            'HTTPS' => $httpsValue,
+            'SERVER_NAME' => 'localhost',
+            'SERVER_PORT'=>'80',
```
Comment (webimpress) [inline test/functions/MarshalUriFromSapiTest.php]: missing spaces around `=>`

Comment (heiglandreas) [reply test/functions/MarshalUriFromSapiTest.php]: > ... Thank you for noticing and investing the time into fixing a 10 month old bug. We really appreciate that. It would be easier for us to include the patch if we had a test that would catch a possible regression. So would you mind investing more time into adding one? And while you're at it, would you mind replacing the double quotes with single quotes and making sure that there is always one space around the '=>'? Thanks.

> ... Thanks for adding a test and for fixing the CodingStyle as well. I'Ve noticed one line that seems to have slipped your attention but don't worry, I'll fix that when I merge the PR.

Would we not actually need this PR merged ASAP for a project I would have stopped contributing after the first reply. And I can increasingly understand why people are moving – not away from ZF but – towards other frameworks. 

As maintainers we need to have a more welcome and thanking attitude even towards other maintainers. Yes. I know it takes time that we as maintainers put into it in out free time but that is not an excuse. Code is not everything.

Comment (webimpress) [reply test/functions/MarshalUriFromSapiTest.php]: @heiglandreas thanks for your effort, finding the bug and preparing the PR. I really appreciate it. I am not the maintainer of the repository, I am just reviewing to get the PR ready for the maintainer to merge ASAP. You don't need to fix these changes, as everything was minor, and as you noted could be fixed on merge.

Sorry that my PR was short, just noted whatever was missing, without all "thankful" messages. I am concrete, that's it. Sorry.

Comment (heiglandreas) [reply test/functions/MarshalUriFromSapiTest.php]: @webimpress **I** can live with that. But between all concretenes it will scare new contributors away. So if we as contributors want to attract more people to help out and fix stuff we need to make them feel more welcome. Otherwise they will go somewhere else. And tell others that it's not a good experience to contribute here...

**Comment by weierophinney** [comment]
Thanks, @heiglandreas!
